services:
  focus-timer:
    build:
      context: .
      network: host
    ports:
      - "7272:7272"
    volumes:
      - ./data:/app/data
      - ./certs:/app/certs 
    container_name: focus-timer
    dns:
      - 8.8.8.8
      - 8.8.4.4